workflows:
  my-workflow:
    name: Tv 360
    instance_type: windows_x2
    max_build_duration: 120
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: 2.10.5
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "single line script"
      - name: Flutter test
        script: flutter test
        ignore_failure: false
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - tv360nigeria@gmail.com
      scripts:
        - echo 'Post-publish script'
        - name: Prepare
          script: pwd # current working directory is /Users/builder/clone/mobile
        - name: Build iOS
          working_directory: mobile/ios
          script: pwd # current working directory is /Users/builder/clone/mobile/ios
        - name: Build Android
          working_directory: mobile/android
          script: pwd # current working directory is /Users/builder/clone/mobile/android
        - name: Process Logs
          working_directory: /Users/builder/Library/Logs
          script: pwd # current working directory is /Users/builder/Library/Logs